name = "RNCAnalytics"
uuid = "e2a77b6c-78f2-4eab-b7d0-1e5d3ed5db00"
authors = ["IPPEL"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-9b89-59de-b6d7-8f2b6eae8f8c"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
